name: 'kapakinoRGBCollector App Tests'
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm install

    - name: Build Electron app for linux
      run: npm run build-linux
    
    - name: Build Electron app for windows
      run: npm run build

    - name: Run tests
      run: npm test   